###############################################
#             Project or run name             #
###############################################
# The name of the project the pipeline is used#
# for. All output will be placed in a         #
# directory with this value.                  #
###############################################
PROJECT: "/export/lv6/user/mblokland/Testrun1/"

###############################################
#                   Samples                   #
###############################################
# The samples have to be paired end. ID_1 for #
# forward reads, ID_2 for reverse reads. All  #
# samples must be in fastq format and be      #
# present in the directory defined in "dir"   #
#                                             #
# -dir:       The system path to the directory#
#             containing the sequencing reads.#
# -ids:       A list containing the sample ids of the#
#             reads you wish to use, that are #
#             present in the "dir" directory. #
#                                             #
# If you use multiple samples, these have to  #
# be replicates of each other, which will be  #
# used for more efficient contig binning.     #
###############################################
READS: 
  ids: ["SRR17380113","SRR17380114", "SRR17380115", "SRR17380116", "SRR17380117", "SRR17380118", "SRR17380119", "SRR17380120", "SRR17380121", "SRR17380122"]
  dir: "/export/lv6/user/mblokland/workflow/reads/"

###############################################
#                   Assembly                  #
###############################################
# Assembly is done with metaSPAdes v3.14.1    #
# -kmer_list: List of kmer sizes, must be an  #
#             odd number and less than 128.   #
# -memory: RAM limit in Gb for SPAdes.        #
###############################################
assembly:
  kmer_list: ["auto"]
  memory: 250
  threads: 16

###############################################
#                   Mapping                   #
###############################################
# Mapping is done with bbmap.                 #
# -replicates:    True is the samples are     #
#                 replicates. This will make  #
#                 it so that all provided     #
#                 samples will be mapped      #
#                 against each other. False if#
#                 the samples are not         #
#                 replicates, then the reads  #
#                 will only be mapped to their#
#                 respective contigs.         #
###############################################
mapping:
  replicates: True
  threads: 16

###############################################
#                   Binning                   #
###############################################
# Metagenome binning is done with MetaBinner  #
# metabinner_env: The full filepath of the    #
#                 location of metabinner,     #
#                 must end with a /           #
#                 Can be found by using the   #
#                 command:                    #
#                 which run_metabinner.sh     #
#                 Make sure you link to the   #
#                 "MetaBinner" directory and  #
#                 not the actual run script.  #
# min_contiglen:  The minimal size of a contig#
#                 To be included in binning.  #
# kmer_len:       The kmer size used to       #
#                 generate kmer-composition   #
# cutoff_comp:    The cutoff for bin          #
#                 completion for filtering.   #
#                 Bins with completion under  #
#                 This number get filtered    #
#                 out. 20 = 20%               #
# cutoff_cont:    The cutoff for bin          #
#                 contamination for filtering.#
#                 Bins with contamination     #
#                 qual or above this number   #
#                 get filtered out. 15 = 15%  #
###############################################
binning:
  min_contiglen: 1000
  kmer_len: 4
  metabinner_env: "/export/lv5/software/MetaBinner/"
  threads: 16
  cutoff_comp: 20
  cutoff_cont: 15

###############################################
#                Classification               #
###############################################
# Classification is done with GTDB-TK.        #

# cpus:           The amount of cpus to be    #
#                 used by gtdbtk.             #
###############################################
classification:
  cpus: 16

###############################################
#               Quantification                #
###############################################
# among us:       The hit game among us.      #
###############################################




